// App initialization sequence, called from main.dart
// Runs all async setup before runApp is called. Order is critical:
// 1. Flutter bindings — must be first
// 2. Firebase — requires bindings to be initialized
// 3. AppConfig — reads --dart-define flags (synchronous, but here for clarity)

library;

import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/widgets.dart';
import '../config/app_config.dart';

// import generated by FlutterFire CLI (flutterfire configure).
import '../../firebase_options.dart';

class ServiceLocator {
  ServiceLocator._();

  static Future<void> initialize() async {
    WidgetsFlutterBinding.ensureInitialized();

    await Firebase.initializeApp(
      options: DefaultFirebaseOptions.currentPlatform,
    );

    AppConfig.instance = AppConfig.fromEnvironment();
  }
}
